name: 'Sphinx: Render docs'
run-name: 'Sphinx: Render docs'

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/sphinx.yml"

jobs:
  build-sphinx-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: ls
        run: |
          ls -a
          pwd

      - name: Set up Paython
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Playwright
        run: |
          pip install playwright
          pip install pytest==8.2.2
          pip install pytest-playwright==0.5.0
          playwright install
          playwright install-deps

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build HTML
        working-directory: ./docs/
        run: |
          make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 30
          name: html-docs
          path: docs/build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true
          allow_empty_commit: true
