name: 'Sphinx: Render docs'
run-name: 'Sphinx: Render docs'

on:
  push:
    paths:
      - docs/

jobs:
  build-sphinx-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/chrckout@v4

      - name: Set up Paython
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst_parser
          pip install -r requirements.txt

      - name: Build HTML
        run: |
          sphinx-build docs/source docs/build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app-wse/docs/build/html/
          force_orphan: true
          allow_empty_commit: true
