name: Testing app changes event
run-name: Test on testing app changes event

on: push

jobs:
  testing-app-changes-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout third party repo web app
        uses: actions/checkout@v4
        with:
          repository: svmikurov/docker-nginx-django
          path: ./

      - name: Checkout testing app
        uses: actions/checkout@v4
        with:
          path: ./tests

      - name: Start web app
        run: |
          mv app-django/.env.example    app-django/.env
          mv app-django/.env.db.example app-django/.env.db
          docker compose up -d --build

      - name: Start testing app
        working-directory: tests/
        run: |
          mv .env.example .env
          docker build -t plw-test .

      - name: Run web app tests by a Playwright
        run: |
          docker run --network=host plw-test
