name: Test with Playwright

on:
  repository_dispatch:
    types: [run-plw-tests]

jobs:
  run-app-dj:
    runs-on: ubuntu-latest
    steps:

      # Checkout app-dj
      - name: Checkout app-dj
        uses: actions/checkout@main
        with:
          repository: svmikurov/dj-docker-plw
          token: ${{ secrets.PAT }}
          path: app
#      - name: Docker up
#        run: make up
#      - name: Set env
#        run: mv app-dj/.env.example app-dj/.env
#      - name: Run tests
#        run: make test

      - name: Ls 1
        run: ls -a

      # Checkout test
      - name: Checkout test
        uses: actions/checkout@v3
        with:

#      - name: Set env
#        run: mv app-dj/.env.example app-dj/.env
#      - name: Run tests
#        run: docker run -i --rm --network=host plw-test

      - name: Ls 3
        run: ls -a
