name: Testing app changes event
run-name: Test on testing app changes event

on:
  push:
    branches:
      - main
    paths-ignore: [
      '**.md', '.gitignore', '.dockerignore', '**/sphinx.yml', 'docs/**',
      '**/web-app-changes-event.yml', 'Makefile', '**.lock', '**.toml'
    ]

jobs:
  testing-app-changes-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout third party repo web app
        uses: actions/checkout@v4
        with:
          repository: svmikurov/wselfedu
          ref: development
          path: ./

      - name: Checkout testing app
        uses: actions/checkout@v4
        with:
          path: ./tests

      - name: Start web app
        run: |
          ls -a
          mv app-wse/.env.example           app-wse/.env
          mv app-wse/.env.postgres.example  app-wse/.env.postgres
          docker compose up -d --build

      - name: Load fixture
        run: >
          make migrate && \
          make collectstatic && \
          docker compose exec app-wse python manage.py 
          loaddata tests/fixtures/wse-db-fixture-users.json

      - name: Start testing app
        working-directory: tests/
        run: |
          mv .env.example .env
          docker build -t plw-test .

      - name: Run web app tests by a Playwright
        run: |
          docker run --network=host plw-test
